### ISSUE TITLE
针对你的回复，个人会关闭项目的开源

### ISSUE THREAD

**Issue by rcy1314** [xiaojiang233/halo-cloudmusic#1]
已删

**Comment by xiaojiang233** [comment]
我干啥了？我恶俗你了吗。
________________________________
发件人: NOISE ***@***.***>
发送时间: 2024年10月5日 18:42
收件人: xiaojiang233/halo-cloudmusic ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xiaojiang233/halo-cloudmusic] 针对你的回复，个人会关闭项目的开源 (Issue #1)


但别来搞恶俗

―

**Comment by rong6** [comment]
我是真的很不明白，又不是什么特别牛逼的项目死活不承认自己剽窃他人代码，还跑到别人项目来拉屎了，我草恶俗啊。

![我草恶俗啊](https://github.com/user-attachments/assets/af30a3d5-3282-49f2-830b-feb50c2726c2)

**Comment by yanjie233** [comment]
笑死了，其实你使用不留名也没关系的，但是你盗用，不留原作者仓库，到头来说别人也是挺搞笑的
还有，你这不开源也罢，本来就没什么含金量，自己也看见注释了，用屁股也看得出来这个项目就是半成品AI写的，还来别人仓库提议题拉屎，真搞笑

**Comment by rcy1314** [comment]
别吵了，已关闭了，就这样吧，如果你觉得我攻击了，我道歉且会再修改，也可完全删除

**Comment by rcy1314** [comment]
[jsdcdn.zip](https://github.com/user-attachments/files/17265853/jsdcdn.zip)
这是原文件，不管你如何攻击也好，我头次遇到这种事，希望不会再遇到，也谢谢你，让我冷静下来

**Comment by rcy1314** [comment]
@xiaojiang233 谢谢你

**Comment by rcy1314** [comment]
<img width="795" alt="1728125395170" src="https://github.com/user-attachments/assets/a4a0fcba-e85b-49b1-a88b-a1642e400657">
嗯，我借助了AI，所以如果你认为是抄袭的，我只能说我问过AI且代码中有AI写的

**Comment by rcy1314** [comment]
<img width="319" alt="1728125966395" src="https://github.com/user-attachments/assets/c47cfb4e-474c-4c7c-aa0b-1080632fc3ab">
已在仓库著名有AI参与

**Comment by yanjie233** [comment]
来到开源社区应该遵循开源规则，你只需要在页脚加上源仓库即可，也没有什么强制性要求，毕竟MIT协议本来就是允许复制分发都，但是需要在文件全部和部分位置留下原作者的名字，在MIT协议处留下源作者的协议。
希望今后可以遵循所有的开源协议，维护开源生态

**Comment by rcy1314** [comment]
@xiaojiang233 会的，我对开源项目是会直接推荐且会改版并提交到twitter等渠道，只为开源的每个项目都能被发现和认可，还有之前吵的议题我也会删除，我已冷静下来了

**Comment by yanjie233** [comment]
你完成了nginx的配置文件是对这个项目的贡献，我们并没有说这个项目都是抄袭，只是直接拿别人的仓库来修改，作者&作者朋友发现后仍然高傲的态度并不正确吧，我们原谅因为不知道开源的相关协议而做出的错误行为，但是被指出错误后是不是应该及时改正呢？人都会犯错，贵在承认，改正。
希望你能通过这次事件了解到开源的相关协议的要求，理解并尊重源作者
在此也感谢你完成的nginx配置文件，如果可以将会加入到源项目并署名指出仓库与您的Github账号

**Comment by xiaojiang233** [comment]
666怎么还吵起来了

**Comment by rong6** [comment]
> <img width="795" alt="1728125395170" src="https://github.com/user-attachments/assets/a4a0fcba-e85b-49b1-a88b-a1642e400657">
> 嗯，我借助了AI，所以如果你认为是抄袭的，我只能说我问过AI且代码中有AI写的

嗯，微不足道的小事偏要闹这么麻，我教你如何清除所有痕迹，这样我就没办法指认你抄袭了。

先创建一个新分支：
``` bash
git checkout --orphan
```

提交文件到这个新分支：
``` bash
git add .
git commit -m "初始化"
```

删除旧分支并重命名新分支为旧分支：
``` bash
git branch -D main
git branch -m main
```
这样我的所有痕迹就都没了🥳

**Comment by rcy1314** [comment]
@rong6 抱歉，刚注意到你的评论，没有吵，已删有关仓库，原文件也给了，我已说明头次遇到这种事，如果抄袭了我会道歉，但的确借助了AI，如果你觉得项目有价值我会收藏

**Comment by rcy1314** [comment]
@rong6 说明一点，该项目从最开始就已经删除过，直到现在也是删除的结果，但该项目没有多大价值，我的错误在于最开始错误的借鉴和AI指向，从项目的最开始的改动到现在，它并没有任何实际价值，（注意）我复刻过你的项目，你应该最开始就有留意到，包括此外的收录，所以参考过该项目（我没有找你说明我道歉），但改动后就出现了这样的情况，我认错且不会再参与任何此类项目，也不要觉得你的痕迹一类的没有的说法，你不知道的是我甚至收录和推荐过你的项目（有段时间你的流量应该有消耗高的）但这样的结果并不好，已关闭和删除讨论的这个项目，就此打住，附上最后一次修改
[jsdcdn.zip](https://github.com/user-attachments/files/17265981/jsdcdn.zip)
